package domain

type Code string

const (
	CodeActiveAssignmentNotFound     Code = "active_assignment_not_found"
	CodeActiveContextRemoval         Code = "active_context_removal"
	CodeAliasAlreadyExists           Code = "alias_already_exists"
	CodeAliasNameCollision           Code = "alias_name_collision"
	CodeAliasNotFound                Code = "alias_not_found"
	CodeAmbiguousSubscription        Code = "ambiguous_subscription"
	CodeAuthFailed                   Code = "authentication_failed"
	CodeAzureAPIError                Code = "azure_api_error"
	CodeConfirmationRequired         Code = "confirmation_required"
	CodeConflictingSelectors         Code = "conflicting_selectors"
	CodeContextEnvMismatch           Code = "context_environment_mismatch"
	CodeContextNeedsLogin            Code = "context_needs_login"
	CodeContextNotFound              Code = "context_not_found"
	CodeEligibleNotFound             Code = "eligible_not_found"
	CodeInvalidAliasName             Code = "invalid_alias_name"
	CodeInvalidContextName           Code = "invalid_context_name"
	CodeInvalidDuration              Code = "invalid_duration"
	CodeMissingActiveContext         Code = "missing_active_context"
	CodeMissingAlias                 Code = "missing_alias"
	CodeMissingAliasSelector         Code = "missing_alias_selector"
	CodeMissingContext               Code = "missing_context"
	CodeMissingReason                Code = "missing_reason"
	CodeMissingRole                  Code = "missing_role"
	CodeMissingScope                 Code = "missing_scope"
	CodeMissingSubscriptionCmd       Code = "missing_subscription_command"
	CodeMissingTenant                Code = "missing_tenant"
	CodePermissionDenied             Code = "permission_denied"
	CodePreviousContextNotFound      Code = "previous_context_not_found"
	CodePreviousSubscriptionNotFound Code = "previous_subscription_not_found"
	CodeShellIntegrationRequired     Code = "shell_integration_required"
	CodeUnknownResourceGroup         Code = "unknown_resource_group"
	CodeUnknownSubscription          Code = "unknown_subscription"
)
